// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaqYTLFkmNwDMa9p-KT5WMQ1JNnm4VBGk',
    appId: '1:228709591267:web:02063e9163e3f6cbcb7dd6',
    messagingSenderId: '228709591267',
    projectId: 'sure-odds-f6471',
    authDomain: 'sure-odds-f6471.firebaseapp.com',
    storageBucket: 'sure-odds-f6471.appspot.com',
    measurementId: 'G-W5EXL89LZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfqFGXBvkwwQAEqa7kBrNEKQcWfycoFIE',
    appId: '1:228709591267:android:8d8aabb637a08590cb7dd6',
    messagingSenderId: '228709591267',
    projectId: 'sure-odds-f6471',
    storageBucket: 'sure-odds-f6471.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbpKn2W9CTm6-rYg8lAlogoBoAfOaymuM',
    appId: '1:228709591267:ios:84deaff3f663d9b2cb7dd6',
    messagingSenderId: '228709591267',
    projectId: 'sure-odds-f6471',
    storageBucket: 'sure-odds-f6471.appspot.com',
    iosClientId: '228709591267-44lu4jl4d7dpv7qpn9v8su9874ah1s39.apps.googleusercontent.com',
    iosBundleId: 'com.sureoddsofficial.sureOdds',
  );
}
